---
- name: Aad-az-grp-crp-proddev-drasticmeasures
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-drasticmeasures-all" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-drasticmeasures-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-drasticmeasures-ba" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-drasticmeasures-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-drasticmeasures-github" }
