---
- name: Aad-az-rbac-mgs-tenant-root-group
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD RBAC groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-tenant-root-group-cost-reader" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-tenant-root-group-network-reader" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-tenant-root-group-security-admin" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-tenant-root-group-cost-contributor" }
