---
- name: Aad-az-grp-crp-proddev-bytebenders
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-all" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-ba" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-bytebenders-qa" }
