---
- name: Aad-az-grp-patientcare-proddev-note
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-all" }
    # Core app groups

    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-argo" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-codeowners" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-approvers" }
    # PAG groups – DEV
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-dev-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-dev-write" }
    # PAG groups – PD
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-pd-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-pd-write" }
    # PAG groups – STG
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-stg-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-stg-write" }
    # PAG groups – QA
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-filters-pag-pg-qa-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-note-notes-pag-pg-qa-write" }
