---
- name: Aad-az-rbac-mgs-sandbox
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD RBAC groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-akv-admin" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-reader" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-virtual-machine-user-login" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-us-customer-contributor" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-us-customer-owner" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-rbac-mgs-sandbox-us-customer-reader" }
