---
- name: Aad-az-grp-patientcare-proddev-qualms
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-all" }
    # Core app groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-argo" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-codeowners" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-github" }
    # PAG groups – DEV
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-dev-write" }
    # PAG groups – PD
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-pd-write" }
    # PAG groups – STG
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-stg-write" }
    # PAG groups – QA
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-qualms-alchemy-pag-pg-qa-write" }
