---
- name: Aad-az-grp-crp-proddev-sashmi
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-all" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-ba" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-mgr" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-sashmi-qa" }
