---
- name: Aad-az-grp-crp-proddev-patientconnect
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-all" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-ba" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-patientconnect-kvofficers" }
