---
- name: Aad-az-grp-crp-proddev-deacon
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-deacon-all" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-deacon-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-deacon-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-deacon-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-crp-proddev-deacon-qa" }
