---
- name: Aad-az-grp-patientcare-proddev-all
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # - aad_groups
    # Azure AD Persona groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-all" }
