---
- name: Aad-az-grp-patientcare-proddev-onc
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # App ALL group
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-all" }
    # Core app groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-argo" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-codeowners" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-onc-github" }
