---
- name: Aad-az-grp-patientcare-proddev-comctr
  hosts: localhost
  connection: local
  gather_facts: false
  roles:
    # App ALL group
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-all" }
    # Core app groups
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-argo" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-codeowners" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-dev" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-approvers" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-github" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-approvers" }
    # PAG groups – DEV
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-dev-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-dev-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-dev-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-dev-write" }
    # PAG groups – PD
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-pd-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-pd-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-pd-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-pd-write" }
    # PAG groups – STG
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-stg-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-stg-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-stg-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-stg-write" }
    # PAG groups – QA
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-adrbk-pag-pg-qa-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-docmnt-pag-pg-qa-write" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-qa-read" }
    - { role: aad_groups_population, aad_groups_population_aad_group_name: "az-grp-patientcare-proddev-comctr-mailb-pag-pg-qa-write" }
