---

# file: roles/role_assignments/tasks/main.yml

### Get info about the Group

- name: Gather information about {{ role_assignment_aad_group_name }}
  azure.azcollection.azure_rm_adgroup_info:
    attribute_name: 'displayName'
    attribute_value: '{{ role_assignment_aad_group_name }}'
    return_group_members: true
    tenant: '{{ tenant_id }}'
  register: main_group

- name: Debug rbac array
  ansible.builtin.debug:
    msg: 'remote_rbac={{ remote_rbac }}'

### Remove Unapproved Permissions

- name: Get role assignments for {{ role_assignment_aad_group_name }}
  azure.azcollection.azure_rm_roleassignment_info:
    assignee: '{{ main_group.ad_groups[0].object_id }}'
  register: main_group_rbac

- name: Debug group rbac
  ansible.builtin.debug:
    msg: 'main_group_rbac={{ main_group_rbac.roleassignments }}'

- name: Convert permissions to a simple list of dictionaries
  ansible.builtin.set_fact:
    remote_rbac: '{{ remote_rbac | default([]) + [{"scope": item.scope, "role_definition_id": item.role_definition_id}] }}'
  loop: '{{ main_group_rbac.roleassignments }}'

- name: Debug rbac array 2
  ansible.builtin.debug:
    msg: 'remote_rbac={{ remote_rbac }}'

- name: Remove all rbac permissions since there is not supposed to be any rbac granted for {{ role_assignment_aad_group_name }}
  azure.azcollection.azure_rm_roleassignment:
    scope: '{{ item.scope }}'
    assignee_object_id: '{{ main_group.ad_groups[0].object_id }}'
    role_definition_id: '{{ item.role_definition_id }}'
    state: absent
  register: remove_rbac
  loop: '{{ remote_rbac }}'
  when: aad_groups[role_assignment_aad_group_name].rbac is not defined

- name: Remove any rbac permissions that are not listed for {{ role_assignment_aad_group_name }}
  azure.azcollection.azure_rm_roleassignment:
    scope: '{{ item.scope }}'
    assignee_object_id: '{{ main_group.ad_groups[0].object_id }}'
    role_definition_id: '{{ item.role_definition_id }}'
    state: absent
  loop: '{{ remote_rbac }}'
  when: remove_rbac.skipped and (item not in aad_groups[role_assignment_aad_group_name].rbac)

### Add approved RBAC to the group

- name: Create a role assignment for {{ role_assignment_aad_group_name }}
  azure.azcollection.azure_rm_roleassignment:
    scope: '{{ item.scope }}'
    assignee_object_id: '{{ main_group.ad_groups[0].object_id }}'
    role_definition_id: '{{ item.role_definition_id }}'
  loop: '{{ aad_groups[role_assignment_aad_group_name].rbac }}'
  when: aad_groups[role_assignment_aad_group_name].rbac is defined

### Reset rbac Array

- name: Reset RBAC Array
  ansible.builtin.set_fact:
    remote_rbac: []
