---
# Owners: Stephanie. St. Andrie, James Dement
gh_groups:
  gh-colonelcrisis-iam-owners:
    privacy: closed
    description: A github managed team for colonelcrisis approvers
    members:
      - username: stephanie-st-andrie_CPSI
        role: maintainer
      - username: james-dement_CPSI
        role: maintainer
# Team puma changed their name to colonelcrisis
aad_groups:
  az-grp-crp-proddev-puma-all:
    nested_groups:
      - az-grp-crp-proddev-puma-approvers
      - az-grp-crp-proddev-puma-ba
      - az-grp-crp-proddev-puma-dev
      - az-grp-crp-proddev-colonelcrisis-github
      - az-grp-crp-proddev-puma-qa
      - mdnizam
    users:
      - amita.gupta@trubridge.com
      - angela.virnig@trubridge.com
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - kendall.smith@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-puma-approvers:
    users:
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
      - stephanie.st.andrie@trubridge.com
  az-grp-crp-proddev-puma-ba:
    users:
      - angela.virnig@trubridge.com
  az-grp-crp-proddev-puma-dev:
    users:
      - amita.gupta@trubridge.com
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - kendall.smith@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-colonelcrisis-github:
    users:
      - amita.gupta@trubridge.com
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - kendall.smith@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-puma-qa:
    users:
      - kendall.smith@trubridge.com
