---
# Owners : Rashieka Coleman, Libby Summer
gh_groups:
  gh-cosmiccaribou-iam-owners:
    privacy: closed
    description: A github managed team for cosmiccaribou approvers
    members:
      - username: rashieka-coleman_CPSI
        role: maintainer
      - username: libby-summer_CPSI
        role: maintainer
aad_groups:
  az-grp-crp-proddev-cosmiccaribou-all:
    nested_groups:
      - az-grp-crp-proddev-cosmiccaribou-approvers
      - az-grp-crp-proddev-cosmiccaribou-ba
      - az-grp-crp-proddev-cosmiccaribou-dev
      - az-grp-crp-proddev-cosmiccaribou-qa
    users:
      - cherlyn.mussell@trubridge.com
      - chris.feemster@trubridge.com
      - george.sangillo@trubridge.com
      - mark.hirschfeldt@trubridge.com
      - rashieka.coleman@trubridge.com
      - thomas.wilson@trubridge.com
  az-grp-crp-proddev-cosmiccaribou-approvers:
    users:
      - george.sangillo@trubridge.com
      - mark.hirschfeldt@trubridge.com
      - thomas.wilson@trubridge.com
  az-grp-crp-proddev-cosmiccaribou-ba:
    users:
      - rashieka.coleman@trubridge.com
      - cherlyn.mussell@trubridge.com
  az-grp-crp-proddev-cosmiccaribou-dev:
    users:
      - george.sangillo@trubridge.com
      - mark.hirschfeldt@trubridge.com
      - thomas.wilson@trubridge.com
  az-grp-crp-proddev-cosmiccaribou-github:
    users:
      - george.sangillo@trubridge.com
      - mark.hirschfeldt@trubridge.com
      - thomas.wilson@trubridge.com
  az-grp-crp-proddev-cosmiccaribou-qa:
    users:
      - chris.feemster@trubridge.com
