---
# Owners : Chason Hicks, Melissa Johnson
gh_groups:
  gh-randomchaos-iam-owners:
    privacy: closed
    description: A github managed team for randomchaos approvers
    members:
      - username: chason-hicks_CPSI
        role: maintainer
      - username: melissa-johnson_CPSI
        role: maintainer
# Team nitro changed their name to randomchaos
aad_groups:
  az-grp-crp-proddev-nitro-all:
    nested_groups:
      - az-grp-crp-proddev-nitro-approvers
      - az-grp-crp-proddev-nitro-ba
      - az-grp-crp-proddev-nitro-dev
      - az-grp-crp-proddev-randomchaos-github
      - az-grp-crp-proddev-nitro-qa
    users:
      - angela.virnig@trubridge.com
      - chason.hicks@trubridge.com
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - kathleen.swanson@trubridge.com
      - kendall.smith@trubridge.com
      - marshal.thompson@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-nitro-approvers:
    users:
      - chason.hicks@trubridge.com
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
  az-grp-crp-proddev-nitro-ba:
    users:
      - kathleen.swanson@trubridge.com
      - angela.virnig@trubridge.com
  az-grp-crp-proddev-nitro-dev:
    users:
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-randomchaos-github:
    users:
      - angela.virnig@trubridge.com
      - chason.hicks@trubridge.com
      - james.dement@trubridge.com
      - jonathon.bowie@trubridge.com
      - kendall.smith@trubridge.com
      - marshal.thompson@trubridge.com
      - melissa.johnson@trubridge.com
      - nicole.oconnell@trubridge.com
      - or.barak@trubridge.com
      - subramanian.namasivayam@trubridge.com
      - sudha.thirunavukkarasu@trubridge.com
  az-grp-crp-proddev-nitro-qa:
    users:
      - kendall.smith@trubridge.com
