---
# Owners : Michael Davis, Jeremy Tapper
gh_groups:
  gh-resolutionaries-iam-owners:
    privacy: closed
    description: A github managed team for resolutionaries approvers
    members:
      - username: michael-davis_CPSI
        role: maintainer
      - username: jeremy-tapper_CPSI
        role: maintainer
aad_groups:
  az-grp-crp-proddev-resolutionaries-all:
    nested_groups:
      - az-grp-crp-proddev-resolutionaries-ba
      - az-grp-crp-proddev-resolutionaries-dev
      - az-grp-crp-proddev-resolutionaries-github
      - az-grp-crp-proddev-resolutionaries-mgr
      - az-grp-crp-proddev-resolutionaries-qa
    users:
      - cheryl.holberg@trubridge.com
      - christine.prescott@trubridge.com
      - dave.legros@trubridge.com
      - j.c.dalton@trubridge.com
      - jeremy.summerlin@trubridge.com
      - jeremy.tapper@trubridge.com
      - karen.norwood@trubridge.com
      - mark.gartman@trubridge.com
      - michael.davis@trubridge.com
      - nathan.mccann@trubridge.com
  az-grp-crp-proddev-resolutionaries-dev:
    users:
      - j.c.dalton@trubridge.com
      - jeremy.summerlin@trubridge.com
      - jeremy.tapper@trubridge.com
      - mark.gartman@trubridge.com
      - nathan.mccann@trubridge.com
  az-grp-crp-proddev-resolutionaries-ba:
    users:
      - cheryl.holberg@trubridge.com
      - karen.norwood@trubridge.com
  az-grp-crp-proddev-resolutionaries-github:
    users:
      - j.c.dalton@trubridge.com
      - jeremy.summerlin@trubridge.com
      - jeremy.tapper@trubridge.com
      - mark.gartman@trubridge.com
      - michael.davis@trubridge.com
      - nathan.mccann@trubridge.com
  az-grp-crp-proddev-resolutionaries-mgr:
    users:
      - michael.davis@trubridge.com
  az-grp-crp-proddev-resolutionaries-qa:
    users:
      - christine.prescott@trubridge.com
      - dave.legros@trubridge.com
