name: Deploy - GitHub Teams

on:
  push:
    branches: [main]
    paths:
      - "deployments/cpsi/global/iam/core_github_team/**"
      - "ansible-azure-aad/group_vars/all/**"
      - ".github/workflows/gh-team-apply.yml"
      - "modules/terraform-github-team/terraform-github-team"
      - "stacks/iam/github_team/**"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  preflight:
    name: Identify change in gh_groups
    runs-on: ubuntu-latest
    outputs:
      only_ansible: ${{ steps.group.outputs.only_ansible }}
      gh_groups_changed: ${{ steps.group.outputs.gh_groups_changed }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Add permissions
        run: chmod +x .github/scripts/gh-groups.sh
      - name: Run scipt
        id: group
        run: ./.github/scripts/gh-groups.sh
        env:
          MODE: MAIN
  apply:
    name: Terraform Apply (GitHub Teams)
    needs: preflight
    if: needs.preflight.outputs.only_ansible != 'true' || needs.preflight.outputs.gh_groups_changed == 'true'
    runs-on: ubuntu-latest
    environment: terraform-deployment-1_0-pd

    permissions:
      contents: read
      id-token: write

    env:
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_CLIENT_ID: ${{ vars.CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_SKIP_PROVIDER_REGISTRATION: true

      TF_ROOT: deployments/cpsi/global/iam/core_github_team

      GITHUB_OWNER: CPSICorp

    defaults:
      run:
        working-directory: ${{ env.TF_ROOT }}

    steps:
      - uses: actions/checkout@v6
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: |
          terraform init
        env:
          GITHUB_APP_ID: ${{ vars.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ vars.APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: |-
            ${{ secrets.TEAM_MGMT_GITHUB_APP_PEM_FILE }}

      - name: Terraform Apply
        run: |
          terraform fmt -check -recursive
          terraform plan \
            -lock=false \
            -out=.planfile

          terraform apply -auto-approve .planfile
        env:
          GITHUB_APP_ID: ${{ vars.APP_ID }}
          GITHUB_APP_INSTALLATION_ID: ${{ vars.APP_INSTALLATION_ID }}
          GITHUB_APP_PEM_FILE: |-
            ${{ secrets.TEAM_MGMT_GITHUB_APP_PEM_FILE }}
