name: IAM - Apply

on:
  push:
    branches:
      - main
    paths:
      - "deployments/**/**/**/core_aad/**"
      - "deployments/**/**/**/core_role_definition/**"
      - "stacks/**/aad/**"
      - "stacks/**/role_definition/**"
      - ".github/workflows/iam-apply.yml"
      - "ansible-azure-aad/**"
      - "!deployments/**/**/**/core_github_team/**"

jobs:
  deployAnsible:
    if: github.ref == 'refs/heads/main' && success()
    uses: ./.github/workflows/populate-aad-groups-ansible.yml
    with:
      githubEnv: terraform-deployment-1_0-pd
    secrets: inherit
