name: Terraform Fmt All

on:
  pull_request:
    branches: ["main"]

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: action-github-app-token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CPSI_REPO_READER_APP_ID }}
          private-key: ${{ secrets.CPSI_REPO_READER_PEM }}

      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "__"
          tokenSuffix: "__"
          files: '["**/*.tf"]'
        env:
          PAT: ${{ steps.app-token.outputs.token }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
